[logging]
log = true

[paquette]
hostname = "173.79.1.178"
port = 8433
game_id = "test"
use_ssl = false

[albert]
to_advise = []
to_play = ["AUSTRIA", "GERMANY", "ITALY", "RUSSIA", "TURKEY", "ENGLAND", "FRANCE"]
to_engine = []
to_comment = []
press = false
use_nl = true
pred_opponent_move = false