[logging]
log = true

[paquette]
hostname = "localhost"
port = 8433
game_id = "test"
use_ssl = false


[albert]
to_advise = []
to_play = ["AUSTRIA", "ENGLAND", "GERMANY", "ITALY", "RUSSIA", "TURKEY", "FRANCE"]
press = true
use_nl = true
wait_loop = 25
