[logging]
log = true

[paquette]
hostname = "173.79.1.178"
port = 8433
game_id = "OD21"
use_ssl = false

[albert]
to_advise = ["GERMANY", "TURKEY"]
to_play = []
to_engine = []
to_comment = []
press = false
use_nl = true
pred_opponent_move = true