[logging]
log = true

[paquette]
hostname = "diplomacy.alexhedges.dev"
port = 8433
game_id = "3_way_test"
use_ssl = true


[albert]
to_advise = ["RUSSIA"]
to_play = ["FRANCE", "GERMANY", "TURKEY", "ITALY"]
press = true
use_nl = true
wait_loop = 15
