[logging]
log = true

[paquette]
hostname = "96.231.122.77"
port = 8433
game_id = "CiceroAlbert2"
use_ssl = false


[albert]
to_advise = ["ENGLAND", "TURKEY"]
to_play = []
press = false
use_nl = true
wait_loop = 15
